// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmXfzOwzAF6u6nKNPR5dxail5axXGLsYk',
    appId: '1:354565385108:android:87ffc8c50b0caa20963d81',
    messagingSenderId: '911848675860',
    projectId: 'mylis-prd',
    storageBucket: 'mylis-prd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg-N-cTLVZyXbbEwNZGgOqZD_ynjWwlXE',
    appId: '1:354565385108:ios:f77ae15711bff8be963d81',
    messagingSenderId: '354565385108',
    projectId: 'mylis-prd',
    storageBucket: 'mylis-prd.appspot.com',
    androidClientId:
        '354565385108-89p6htlbfqq6toe7rfbbt944ganscghn.apps.googleusercontent.com',
    iosClientId:
        'com.googleusercontent.apps.354565385108-924ham2gucchip58hck1342a0795q1u5',
    iosBundleId: 'com.mylis',
  );
}
